// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9i3Lctpbgr2B6pkp2ptWynNxUrqpSdxXZTrTxQyvJuTUTecdoEt2NEQkwACi5k1LV",
	"/sP+4X7JFg4AEiTBR8st2bJZt+rGauJ5cHBw3uevScTTjDPClJwc/DWR0YqkGP55mGUJjbCinD1nV79h",
	"Ab9mgmdEKErgL1J+wHFMdVucnFSaqHVGJgcTqQRly8nNdBITGQma6baTg8lzdkUFZylhCl1hQfE8IeiS",
	"rHevcJITlGEq5BRR9t8kUiRGca6HQSJniqZkhs5X0BphFiPTg+BohdJcKjQnaE7UNSEM7UODp3/7FkUr",
	"LHCkiJCzydQtjs/18JObm8YvUx8MJ4Jf0ZiIs4xEsOUkebOYHPz+1+TfBFlMDib/uldCc8+Cci8Ax5tp",
	"HZAMp0T/twocvTtcdke6VbG3/f/3f/5vdUco4Ww5RVJhodA1VSuEUUKUIgJxgViezomYAiQizhSmDDGO",
	"rldUEZnhiHgAcacVAMhfE87IgG0fp3hJAsCDIbo6HmGFE74Mdn138677iM4UVrk8hxZ1aJpviC8QRpKy",
	"ZVIFLmdIrQiKyRU1sCAsTycHv09OBMkwwGOqxxDK/PM0Z8z867kQXEymk7fskvFrNplOjniaJUSRePKu",
	"DtPp5MOuHnn3Cgt9nlJP0diBP2fjo7eIxrdyVY1PbpmND+W6G5+8jVQBLc/yNMViPRDgSeLDWrYD+xeC",
	"E7VaT6aTZ2QpcEziAIA3Bmp1teUcrU28yVvbBOBZbVAsV4MuV6sjzhZ02YST/qav5IIuNSiqlAHnahUG",
	"L3TTcAhc3Cn0e3v6sqXb29OX4esuyB85FSTWACymLkcLXb+fsIpWzXngZ0QlwgyRhACFpwzN4WdJ/sgJ",
	"M0df3W9CU6rCpDDFH2iap5aSaZqWERERpvCSaCwz2CSR4ijPYqyInk+jGcyppxpGuk6KUYFYpZTpaScH",
	"+8XmKVNkaQjSdCJJQiLFhV5017Av8ZwkZ66x7phHEZHyfCWIXPEk7hvAX9dN20GcWci2HIj7jGKyoEwD",
	"a0VQQqXSAAQ4GQDOCSIfSJTrR5eyjvOSrfMdVsc1MwKPAG8vVSSVfVs2uHUz1YdwbDqUp4CFwGsApBJY",
	"keW6b7RTniQ8V2eueR3hi3FCaN7xLjX4omiFGSNJEyanZEEEwF9xAL1tiRZcwN/+i5Th6BIvw9fbfhsw",
	"AzANmw4veS6iIaNHBiobTlCHu5mt3NW0gGDwJDSgF3oWckaX+rk71UgoA2SjtSkSJBNEavRAGAn7o96F",
	"Zg6WjMQoKvuiheAp7O/oMECiM/obERJmbFyCk2P7rXLjrsxvJEYGN/UtUSsqy2VZpmShyafZ+gydEaE7",
	"IrnieQJc3BUReisRXzL6ZzGadKeTYKW3pcmVYDgxLLJhAVO8RoLocVHOvBGgiZyhV1xo+rngB2ilVCYP",
	"9vaWVM0uf5AzyvXlSnNG1XpPs5KCznPFhdyLyRVJ9iRd7mIRacYyUrkgeziju7BYZm5/Gv+rIObQZRD9",
	"LimLm7D8lbIYHhRkWlqOvwCZ/knv+vT52TlyExiwGgh6h14CUwOCsgURpmVx0oTFGadMGTRPqH6/ZD5P",
	"qZIOXzScZ+gIM8aBJTevTjxDxwwd4ZQkR1iSOwelhp7c1SALAzMlCsdY4T7q+AZg9IooDBTACjmdrHrb",
	"7QIJCQiz5oNuP4zp3uBLyvtmUcXbpF35RnTjJd2IdujmBg/dA9fadCQWd08sCkaiCsyXQ85mEBPS/t7c",
	"NHmRkXR9AtKlz9oQrs1IhTn+jWiFU/5Uz/efAmcZEQgLnrMYYZRLInYjQTRQ0dHZ6RSlPCYJibXoe5nP",
	"iWBEEYkoB2DijM48fkPOrvZnnUtoEhbyIaPCiO4k4iyWIe4N+hs9WkEzrnBCY6rWBQ/nLURPs+AixcpI",
	"Pd8+nTSFoOmEfFACd2kBi3vWOOL6/ampB/XACCuDXEQa0kcAvEitsEIOxsCcaThnPMsT+Gm+hl8PT46R",
	"hBujYQ/t9c41XaNpmis8T0hAGWgQKchVnoNMKcn33+0SFvGYxOjk+avy378enf3r/hO9nBl65WSqFUH6",
	"ZZoVvCYlCchW2MeHLobVUIXKkczXigT5d83CitdBreIxiw2SwZpEgROmjyH4QKr+yHFCF5TEIEMEL2hO",
	"A8Tu7fGzezgnbxESL0kA3d/C7wB1vQ2gvgTehEuyRqaXt3+rLKBS5lXuv/JQ9CKw3nJYnauP4x4BUyOF",
	"DpsryLEZ6Su4uTaEwlkm+BVO9mLCKE72FpgmuSBIFprAYpeeGlq2wB1RzdCsEflApZJNiuc1Dd9RO2RT",
	"npuWgENcS7MFzAfdLk1ejSIjwDUW34wsrE+W+zdthn5l/JqhyGsoCDoE0JF4ip4RRvV/NYReYJqYRQ3j",
	"VNyYTcSsYYO3hSAOFAO1b7A8vpgoTBMJDwhnBGF95ZQ77igXAjgQpc/U8a4aqU89klbTAmKpzgVmEmY6",
	"p23WEd0OKZoSM1OxNFX0JbHhi/S6LBoqjjDjakVE5bQ1A7SrxwpzIlIG9S2/5ClmSBAcAzbZdoiaO6H5",
	"OgcdPOe5sisulhckaHwO1z3+mTBi3unw7meOlZkti5aGqFShcY0lUD79ZsUoz8y0/rv+/XfBd10QLIOC",
	"Cno0F5QsHiPTomQd3Jw7ctBOBwqIblQnELqRBnYDJXb9Biij2bYrmIZQrgBAef6dl6WNQJ5VyF8Boykg",
	"JV+gc6EFrRc4kWSKrNXAN4ro75PpBBpsbAaprc6OVfvVDV372bdgVKHZxMd1BnspsY76koS3G0fpjOnE",
	"/dNQPdilJnn6I2jH6Twh9T8c3TjBQkLTszWL4B9vrohIcJZRtnSadn22v2kWV3c0CuBjdiL4UhCpv73V",
	"ko+17mUkck1f5YmiWULeXDMCYzwD68IzooUeKrVIoTsNO4PnTPAkSQlT9in1Nt763A5pU0CttUUBzlOS",
	"cUkVF+sgLDUIWz80AO5/LID/IiFEtZwAfHOwhT9CZ2Fg7J2I+cE/F/PL0NMxeLugy7rtfpgl6GeqAt37",
	"LNi/Fuz8GYkEURt1PmYJZeQWs/6iVBbqBjDIcndirzjTSLCZD0OosxlYcPb8Q6aPL8wsCM4QKRog8+bA",
	"c6HHjvMENB80JXJ2wfSbZltQid5/g+z/3h+gXfSKMi0BHqD337xHqZWqnuz+7e8ztIt+4blofHr6rf70",
	"DK81XXrFmVpVW+zvfruvWwQ/7T/1Ov+TkMv66N/PLthZnmVcaFZdMy9Y47pe6nu9Yif4aQ7WaHsekdly",
	"NoVhKEMrveRiPHJFxBp+e6znfb/7/gCdYrYsez3Z/eE9AG7/KTp8pZmYH9DhK9N6+v4Agb7LNd6f7j+1",
	"raUCTnL/qVqhFGBo+uy9P0BnimTlsvZcH7OYeo8z4zNR3csPJUj02/aD1+WCPf+A0ywhGnLoye4P0/3v",
	"d59+a480yA4c5VLxdPuoOm28yEYmtIYqvefUtNfoGMEqUEjr6B59jfuG5DRx3vxeNTBlq7WkEU48j4dR",
	"LTzakEYb0l75wg+XB2yfW1iHQuy7Ga3h+tS06oe1OjUBkHlKHs8YHoSq7rQOi3bOx2XhpGyNZtcrGq1A",
	"WwA9ncaqfxpwCQwIJq+LWVwb5GTPkEV/FhQSh51Z2EmvfngAYgcYb+XFLIMOsOqGFRJfpWngDmoFHmFA",
	"KTu91Kr4oK9jLz7oRpqjMdRbYZo4EgPyse8vsRVZudtHr+nx0gNVw1G2AfLIU+2UAq6BV6tHmyAsJoLE",
	"re/dqW3gXrjWcfsUntV5OjcpedL6lNvP/otu5Xj4OeKMkciKvMVhhzylgAc+fha+8fYzOn7ma1NqM4QR",
	"w/R85dHoGr4XVpliFkcRHQ3R67aa8R8rrtcRZvAsSaPIBA8unNA/jcZNWalfEZFShpNpsWbjQ6a7TRFR",
	"Udtx4fgNS9aTAyVyUkPN2q6mHgDbj9KXAJuAcINZXRx2KBVX5cZCVds4Q4XFkqhh75O/lHPoF9ZDmSGH",
	"bckb56CFp7XcYUyknqGxtZSoFY+rV8rXzrxlBJQVoInR0vv6lMjK+roUHV0r9kbualadtYDCsX5wBFWt",
	"RN0Suxotoq5bc8cfScwNChWEvJxoK2Q8uGm7xdtR8o6xehSWHTAsfOSxlFXtXelU/pZJJyZvhEW1BRdT",
	"BL8W8wa/lotp+eytsAAY+OuGXYNK19aYSkVZpFCiW8spul4RYaNQqCKpljUMzigSIyzRxaQgsReT2YVe",
	"EzFist45KcNhfswEj3Og+sAJLSlnP+Zyl2Cpdvc1ZlEifpzj6JIwAOxwE6XdH12QaB0l5BfOLx0euAP9",
	"iSy48DVxhwtFhPe3aXBK5pz7LcofNjnqylIaUwfa1FfTOoy/wLZxvDU3gXMr1idxvbdKZ+qD27k/msrU",
	"9no78hIapI2uFFxDC8TKt8hdW6NAtxe8quOt/rIhjamtuk4nap8rqwh8Dy2tp1mV4gSJTfmt6nRofpej",
	"LumTuxh6JzHITG81h6P34OfmPTidWMXAsBN0TNT23A7NuG9k2MvQ/4rMp7m9wEaKQG/OCuGxldFNg34M",
	"55VBoJHVZYlh0WJm3M5N3eYpfXM2eAu/VdUFbhvhG62/PKPLVv++GL7VxzJ2DyRX+Onfvj/AT2az2eOh",
	"oKlO2g6owra6EbgKAtYn6ERZPgy7q+swXMF0ElN5+TH9U5LyofcrNELdjynLJ8WgdnVDQdviyGDVGtKq",
	"RQ0xNcA2NL4Zq/pPLOyDfySoohFObh21GlqoHxTb/FpOHvrqLSj02S0y9M33/vDU9C1kqUaUcIepq9RQ",
	"tr+plUAya9Ae/sK2Re0HntyoJSrXLcR8v8Uagjb80PSSJyH31XMvMhNHil6VCkGrCduU43B6zqDbdZV1",
	"3VjDBX5rA9dh3zdjmjBUK8Cp6qVV7qA10doTsR7sw2FQswyHoCDXUpE0blHQmo/giuvijO2SmkgORvET",
	"LfULJrsUCNAQZbZlZTMNo4UxwLt1aN4JnuipSfbABfxXS4syXyzohyky4YwrkiS7Uq0TgpYJn7vJYP0w",
	"O15iyqRynprJGiUcx8RMAWtK8YeXhC3VanLw9G/fTyd2iMnB5H//jnf/PNz9zye7fz+4uNj9r9nFxcXF",
	"N++++bfQq9twSW3QacNJnvCERgMfibdeD4NWN630v+1J9b/6av6wHC69RBKWyCHbV/PUSmCaGNNZpHKc",
	"lI6vH0sTLUvkk8ZSBbABHWjaOgN3ATcNSRuPXjPEDXedLs4A4Ghsks4op+EY9Cv2wfux7tL+uzCIsJZW",
	"Ms1dOv3irdS8eoQES3VGCBvi9mzRwnj5EubCBiydGu7jXOhgbqU22vABKPpUnoBNecKNRbYGQhpqemy1",
	"cgMGKNsX5CrehFLFLX4L3s2orKp6Eyfhi+mD0Ue/Ao3hbMr1llDzUM3HgHYe+va2dQ9XV1jE11gQUP0Y",
	"3znKlvZpq3pebd/mbtfgogG2Z67Zgr19o7Q6YVvMG/AgDWfQ8dXhJ/yaCBK/WSxuKaRU1urN2vjmLSTw",
	"tSqCVD41tfeVz5UdBL4HBJjKbQ8yAUULq3EzEWM0lnt5TmOTXYbRP3KSrBGNCVN0se4UuPGSMNWqkNXk",
	"/HAJ6c9Mk3A2H08V1jKG10I/n8YtdV5fWmNkDeCQS8JPnCt0/GyToYp7bGAYXueb4rKfucs+cIK6js0H",
	"SbGP5iqm1QNov3oNRrLHwp5BS+M8ihlemlgfIC2GzELiuijJY/3lekWY+90pzOcExfyaWWZbk0IbMtZE",
	"ItfuzHhN9z7RZjNF6+Kpum3/mx6wxbdS7pk1bd8YXxl+mxS+stnbUfjmEBuYyUqAFTay7Jw/wxCn+CZX",
	"bxb2355t9DakvbJIb4rAV3/WYOeakbb6tUGhfVmjh7Nw+b6cC1NCiEKCqFwwEpsLtyAqWunrV6T8g9iT",
	"TgGsxOS2aPYBkXMxWeA8UZODvxox7YdoLgi+1De6cyfzNbrw13UxaRp8S+SSdbbsM1i8XVP3whVXOGlR",
	"w+pPnitsaKaBkYyW+n1O0LG8eBd06q5iAKppAFnr51/bcJAaUXn5qSMtYiovTSB+80ZmWK3aTDMC4srW",
	"SLfx1HAwfHXMbh4C5ngXju6gUuQw6095bH3+avxirUU1pR65IolNfcmvSayXZVsbyiRM+JtmMilouCEG",
	"rgmGpeB59tO6XSkEjkfokqyBNc2IAFdO6KZBXJgDy/nnsNyKlsTT5z36/XD3P/Hun092//7u993i3/+1",
	"N3v3zeN/eB8HaPhAcfiW4StME/1mt+R1NAkWvYvuzggVPYt75DIAG/CBbrIjPyN8PeyZvpZWcoFy1py3",
	"OMeN5g+yTbkf021pyeSJvrTtiysStrh1FO75xvNYcRTZXK0mK3LRoeQ1XSIM8EPDCMJB6ZX17yP69tix",
	"52uEjXopZ1TNUBnmVvwISQsO0HtpIsakSTkzRe9T84MJAtM/rMwPEO4G6O2h2j8Oft/f/fu7i4v4m8f/",
	"uLiIf5fpKoxXZQRtmUW1novatdi1mq8+lq4c88x2qNOHwJghUtoI720iWqNJRwJCm0RDn6lZQKfiePT1",
	"GePGvsK4scaF2iyErNl9u7kGWyL+Q5xua9MywUpY1C0IhWf7QCXJao9iwC6zQEcqn+sVUSsi/Mw1aIUl",
	"mhPCkBvAO/M55wnBzNgu5iT5mKIAh07rZkaChC1ZlqwdaWmoiFr45WKfG52QJyQM4oPbj7rJDfdM2nfi",
	"nuXxY8/+sMXvCV54rGysoX/611hWDn6YUcn1+Kkt0LEaL6nbigHKv3LUqb+lAC8/3fAIbmH+DQC+OKBZ",
	"ENfCnr7BZlWn30aTkSX45O6/wTMZZIBuMo6jT/CXmlE0zLD00wDwq6PGoa5oaKhPo+2OdD684BQRcP6U",
	"IkyGQ/kr/VR80iQV8t+VwCNe9bEZHsJ/FzyDS4NmBTd0TW0REstGUFk4TqwIQxqTPTJOZYjJaeEzNFSH",
	"HXmLkaSl4WZv0aCnoWRCb8XSeI48fckXfYxqZmCcbZxXsZlFkHwE5d1apsSmEqHjdG2TLjZvxa+tMkcT",
	"Qrh7tpTTi4QuVwodacLIEx9ZPU+fZvEYTRyjQuG0kT7kMFdQfMNTg+R0170F4WN/e/rSnc7b4/IWgg0W",
	"5dK4TWbCvSX/6xRpFAEeIKHs0uQfgvncC9Zhcb6toqdN31ODVzlBKwwGoQTAsR8tXB2gMieqfWmry6og",
	"jalYcQvUMEPveldyN5w84AgaevnlnmGFy2X61xxC64FnwG7peny0oIkpQXL+8ix88c1iLsm6cxG/kvVG",
	"k1+Sdd/c9cveApXmEgcd/HCSMIAyuCwQ+lrwWx66ty+NVFxQ1Qrysu2ha9oOfZ9XKEZGlZTmbReYBFgS",
	"w4/qVxiIRxwLIgvngd6No0eOtVxxqbSEeZBxoQZE6nQAqFhs6ORf0IRYzxZDZ5153mZ3Bge91GZzdE54",
	"wwzylaGPiuEqP58WY1d+fusmsit0HGcNKThTpI2cZwmmDCnyQaFHb89f7P7wGHFRT35uR3Dno69c2/uu",
	"2z3X3WyQQc3DQz9+JvGJMppxoWUPmGWGXtnKh4SCZupiAou7mOgVXUzMmi4mM/TMGFXgpSka+T4T8NNk",
	"ars0z+FmasxuYZDo7e1IY2GbekYVuyywrbjIOZanRNAIHT+rL0twrsyqmjIKj0nn1BkRNuoCqgrM0H/w",
	"HEQ3sxjjR5VqQWuBU5pQLBCPFE7KopAYfJL+JIK7TH5Pvv/uOzhbbESNiKa2g8mUEurz3dMnj7XsqHIa",
	"70milvo/ikaXazS3JiJUZFaYoeMF0rJhAbGpcaOqbgZotd6nZs9LgOnlhdNPtduJ8VzyJFekMBM75Kwl",
	"dkKvuSKGVSnSjYPpVDcFsWFOEL8i4lpQpQhrSUJPROeh8WvIrr91fAmZtIurFiZWCQnZs19Y/xnPLGVF",
	"qniMNB+tT6P1yesBd2Uzi5Ppsl0rE4wZ1iUXn6r6Y/h5vMmfXmlcHsQgfYWh2aN2+EvVDvsp0du0hM02",
	"mykIrYNs6blUkwOMhq2lnO+5q6Pr/KTKYNE5cR5RJEZ26CGOUCURDW+1Q/MNW+nVdtutDosmPa00/pi6",
	"voqkWdKqF3Vfa4k6ml6ttYDie8nAW3dmDz88dbdUt99WxO7E6Fuj8uCoW2g9RQR4b5wka0RLZ2Lvaqzw",
	"FQERBVQckavKBNEdpKJggLJd1ysayvC1sRa7OPGPD1qNGz70m2SxmbobM+g1qlKrDdXmUNqGRqck44XX",
	"cdDws4CqKPU0nAOqv7ihXeKRXLR4mT/KOBS90LxEyhV5DCFJplTGsNQ3emjbJrjXYBWJhh5mSdWp3k5o",
	"jcKvu4zRz1RVsyDY+mABssFzpk4KEdl5m+41nE11G0eCDBbtSCMB26DMmk+Ig9CONOJ16WYKU1bMZn7Z",
	"6jZh3ZfRbcoNu5qycElLdmv3ud/BpByqUk6v6cUMz8opuaLtQXvCfoWAQOmViO5cbyNHcbH4xqzTNvf0",
	"aUsm8vpua5lL+ldjs29bRAxNDDkTI6fkLP2jauFbi87gftC0pFaZlxIV8GX2ys8PJox6bZ3EUdGUWOL2",
	"wByt0Y7cqfpZ76Q7VT9rLQ/trHY+3tc6wKkNLZdTYsdpziY37yCQovpjwG376jcsPsby/7zMmYqusKDg",
	"tn9J1ruVPNaU6c14Dvw50zAOF/7MW+68FkA0oKsY6od5YrZGWCzzFBiZXEJUu8IsxiI2mViQXDOFP2jk",
	"0TIUVAG1SlKJUlvXyM0kUUYzyLy9BHfMqcYoCtd7ja4h06xdBMpZTATCaI7lCu1GRof+Ieypcc3F5TPa",
	"oq/UH01wjguzKXN529iVnDEnQdqFDiB1OWslKZVyg8NxreimH683WX+JJL+PV7bopnddXTWODisVjkri",
	"RjT+QfwpR0rkRB9dWR0tSPNs9E7L4xnacuM+8RarBXdGoUfyMdLzg4odKzDnkMQaXswrrLcgsaLSmhLg",
	"12Lpw3UWFaNYgCBvoLrHVnEvfLQsQA2Me7TCbGlo7keAOaxO51kYd4uaW70MbOM19Jg3vchfzs9PTKSy",
	"pgQBqQLPIhF4u34CG5YzkiHBuUJHhy3Ml5TXXMRtDJj5alwKcrUy1qLmugq/32K8kGH3kmZGbfQbEUX8",
	"X8DQe0kzy3e7GrdXXoewg7lK5CBgnL88Mw4IUCNz6NL16JdkPXz0S7IePji/bEvqA5+2A/32GsTntvYw",
	"8Il9c/VzBpOWqnMNsrRSKhso3TCzkmHyjaYKJ0Ey0ivQKO4JNM6EXYSP22wUsBRJNF6W/F2XHXATcUQ0",
	"xREnTWBbMXzNItQhqJhEb6HNi8Ic//b0pa00zVNN8hfKhnXMsYSvM3SsoM6HYWMI+iMnEFwrcEoUKOvz",
	"aIWwPEAXkz1NEfcU33NK339A6x+h9RADZUXkKY7v/qUch5FtdP2WqolV5UkYVrBxaEHbwSoNwFo4d44i",
	"nCT63YwSzoyUGsSkK5zQ2ISUt+CUHs/gm2EFOUtM9hPXVbO/UEG0rHhdSMLorQQLAnjuaAR3mGkYYJCT",
	"4O2yq3b85nztDtilt9VnoZlqWAmRlo8GM/2KJJmhZWCfKnZUpKJSKiuMFRupdab+uYYw5jjFSxLIOtqk",
	"hC3Ji099GugoEtT9spmHA/W4UIajy0GB7u3JmVvrjTYXbjI8deSyNDylxjlwU2rWzxrMNrZlS71bkmB3",
	"GAJTZ03XgZXiNl/mdCJhtqF6wXKVyHTsVQjeXgVoJhio9xsGkHLNwQFkhqOOUeBz71Dhky+Hn3oQ6rV8",
	"2N7lIYVQp2ofCl0fyODgzE3WXg+/mYeYX4Fgb51xSqszMhgg86TMJPvSRD8Y67iKVqXgahRJh6+fkXiG",
	"nqeZWu+xPElqs9uKtIhxtaJs2ZLY1hu17za/qreHpBDFSj8q4iPFmd74X5dkPQVlz43R9oQjNpoH46y4",
	"QSO9/uLlsy4KphnpeM3UiigaeXnXC0nU1wdp0miO4woLynNZmLFgGXKGDr0Ex3htRFl4Wm1x+L9Ki94U",
	"uYXdBM1OirI8cEFe4TVoJYmyqiOQAOBvjBKaUuUodZkCAyh1wQ0b9SItgoMrwTVEQGAw+Bua4moueYbB",
	"UKOGoxLxDP+Rk8Jzw68qJyV84OAR50Io7UPoeRdgY4EDuxyV5t1RXC9TUHJlmApGPih3V8o0HgW4jwyY",
	"TE6oiDNJJTD+MJZelnVQsEYh4kBmd1qVSvS+ndoBMtsI8CNkCKMFuXbKWXOmGdSvKi4tnLhzqzFMUDV1",
	"ldEdwj7d0VpQOpdEk30wMpkiVAlpa0emArJMyIwzSaYoZ4lmzdY8N+sRJCK0AKUVPsF9niEihN4OkbKt",
	"foIgKaaMsuWxIumRpph9dUxlPpf6YJmyyGXXCYAvK5tq8Fs5JDZN3EG7rYAjadHTIYtjl2JL0MCLFHSr",
	"jrKBu2kdz4t9uEVJlJucZICnBpB6GAf0hCwUyhlcHhYjnlLlaZUlEVAd0SgvKguFczSGA/TI+n7OSYQ1",
	"M0zhM1ieVzkD7SsvvwIIrCs8pLeDRo/L/QhiQWcwsL4ns5FC2XyrnTgXIJ7EID1ihq72Z/t/QzE3Tr1E",
	"eXMYLKdapIY04tITeet4o3f2DZGKpiBCfGNuG/3T2u4jniS29iUyUSCF75ieVxCglG1jG0kCqIEotPY4",
	"GpY1LPRm1J6zJusX1ByZnM02T5NPPe2Tb9I+go9Ue2JNLno0u2WeBCAg8MraN9x5vh+zyXTymiv47/MP",
	"+nGaTCfPOJGvuYK/g97wxqGuu0SBaVMkla+w+/2J4H2uSoPQ2/S7JtgHZNQvVfLDnezqh2vSRx2brvtN",
	"aeQVlB3ZfhI1vWPPj6ex1/KbvjxVzkRL+5l+VqS+zEHuxBBbS2Qhs5V7HoExsG2NDBfwFGWMqzJT/S2Z",
	"t7Ix3M5myvLGzYP1UM7OaUqkwmnWkb/CJI0HP8Zr/USbqJnhSStikpDbzGUpK3TfZL4lYUS0aMgPkXk2",
	"o+LZqnhxYmdtjlA5Spl80BSBNf5x6IRneYK9XLtGrpuhU4LjXc10Dsym+NHR2q8M526dUyF5neGRDQ0B",
	"bWW18DAXS8z0q6DbaS50yYX+85GMeGZ+NeT0ccHrTW6tU7TOykFafM1IUIrzvGixQvwaHB3AG9r8rqUC",
	"dAFOoXt6rouJLQzaVrPd5xCDVkfLT1sgwrQ2IbVLUWyY1h3peU+XNbJKp+xhqv4TTR29BGcFSd1AO9pr",
	"nfRyGPrvFo5NCF2WGBndBNMF36qwUfEQ/c+zN6/RCQdIgFmxTQ2atyCI4a71GxsDt29XM2u8Xzzr8t2p",
	"PyInRESEqaBSsPzm+D972AZzqpQgKxubVsENVnTIAS1k+dVN6achFhXfJnc6S6qshjR4IqcdJpGKR5YX",
	"efQzVb55RPNI1i7k62/HGIYxGmmMRtorL9FmIUlev+3GJZUDh4OTqt+rEUrFNzpGHH4GcUqidhwDS60V",
	"FH8MWfpSQ5ZqVKfjkjdKQ1a1qFWmYpj7Xz1+oNf1z7fo9zU+k6uybc/WWyJb6i02C2+pQuQjw0uqg91v",
	"diSn3jhMiFCntu5IrbKJv4Mm277KU8x2i6IftUgwMIjrscMJyfI2odrl4C54XC3Jg52tNHDiKyI0Mw25",
	"5MF+MbfGhzlZ6EsPE2s+G72A8zzo9vTu9+Hu8t++uIj/vT09dtYhRJybJAtONuALuyOjhhR0udSEMgRJ",
	"o28wZugrMqSeXeW8z2yncJ0UN6J3TJV9VFUGvchVmSyQT8Z8beCME2GCFXyhTtSwLC2taykHbm3izdja",
	"xizF27SrYqq3SvVWU8qcjjjFWWbzqxydvG295Fke0j6ayhCtIWMtVSOcMrRVtdqqKr0pCNz6NShnJraa",
	"g/NyGvYgtOymj9R3rasneK4FEjeBU+osJxUujYErEUo1JthR066yudAICd1qht44g7L5NQPzr70StChu",
	"sHEp3ZKsh0o/eMfYWmW7UuC3WlC36QuD0yyhbHmsWexgKu2CrM+JuiaEFYVBoKsGxD1Q6iLMpiPCxqeE",
	"Ppym/tkGdtxFBs/WLMiFlV/rNQc83yFwNrAWbOPGBSGungpGceONCvZ2e2AgZtGiDPMoqo3qmFEds+df",
	"uU0VMl7PbatkyqGdUma8r59YtWI7r1m08dML1H5Urny5ypUaDel82GsKFpfn7pF8XDzbNjNql2ahJzjf",
	"JMpoROFR1vD1P4bSCK7F1NYfcx3Ka68wZcbXMcRRGE9+xjXquN5U3+nnOFpZv+TqUMbk7QbQC/bZmu67",
	"er9xO0MSDDjjfZFooAnpu8ovEHiHuvHvFjouv/9Harnw7UhpZ7IAp+w54mlKVUcZ/ggaoBWWNnIW6vCv",
	"WdTiCu8G/rnD56MY3HPpCIw9xINtE2WdSehi8wER63YXKpTtCI1NVm4cL4qMOlow8rJMdaknINnUmfVv",
	"aTunaqOmvkAqgRVZrocrC2ojdgCjzB1Vw37/s9MiupqOtjJ0Pb1PXe8JyVhMjt7zMjVFp84hL4Op4+Yx",
	"DUhvVT/cGzifRqXLHsVHtT3EIULg1/lKELniSdw3huf0EPQ1KXIL2ZMN3hB37hrQ0YrTyARJufL+bo+a",
	"blZPxlf8VVEh5L5wJldbivE+O/ulK8Q7E/QKK/IrWZ9gKbOVwJK0x2qb70ZPIVcnRd/PI0S7sqTeUGq7",
	"cwDQ8GjqEOL4ppvNXJOkf8w91qE7CtvU2685vrggzq7gza6wxXJXISLX9rbb95waNZHKBbMCg8a2CCeu",
	"vkrM2Y6LmUYmeMNzvhvFy7sVL6NgnvCzfLkk4PwL7lL2cCKXWhvgZ/iwKXqC6MK579cZim+fBl0/R/ly",
	"q/IlRNjczu5ZMtMGjs6FskW8wTJsYE1xtKKMtE51vVrXJrA1q/UaLiYvME1yQcoq5ibohcoy7oukmVrb",
	"OBUIc6lKB2W02CE6hWWiKMHCeLE6rz/p6iPGBM1zTXmICZjhV0QIGhNEwzZg2U3inMNvATz0BsLuDtDF",
	"5MwwNa7AQLHTO0cbmZFoF7N4t1EYvrUcYlPNIF0leCATBQaUSBd6EM5tKs9WSl1rULUo+M7FRZ7T8SUY",
	"DQOjYQB61C7PZraBeuftmgdqo4fdNgONqr6btQYjF/jpjQyhIxmkHas/BaOt4Uu1NYTIUt/db7h0Vt5+",
	"q4JpZwEW4RI0505dhq5XXHq50u19X4CnGu9niMz4Qza7YbFvP1n69K+Pdc3cMDNOp8LaYvXwut4FcK+x",
	"NNpmdzEGxi1uol1ulOEOnsNmFoRiAxb3oNT2OU3Jf3KXp8jlu37JjX9dbQ0aJn9yRsq4OSGtJxDMdnz4",
	"+tDFWh2ePj/ce/nm6PD8+M3rKboGcUb/WOWBTa4GqIYmEI8IZuYNcT2L5MCQGRgLRaM8wQJJait9Uqvq",
	"x4LgqSmH+QG8l9Ah1IbCe6/J9X/9BxeXU/Q81/i3d4IFdU5eOcPpnC5znkv07W60wgJHkPDN7bVWlgs9",
	"upj8/Or8YjJFF5O350cXk8dB8mT01GfRisTWjbduFChfbGlbuQSDXB9jhGJ+zRKObZ7c2KKb9NOlKJq6",
	"rzwzijtk0zYHeIleVfWRqOZ5BV5LqJ8Fjsgzzzl4qM5decjV+Xa6dg0aHSZKHktU3eJVG6/0M1U+yQ0H",
	"T7dcVDfouxv9Rd8zlz8GRwBSkmKaTA4miuD0fyyg2mKkkhnlExdACySlVofxnOB0YrWbE/eCVno3woB/",
	"rw7x7lGo22PLTNjSC0bFHyVYH8tVpToDX5jXA+gDiZdlbQ2by4MKyG6skVDOLvQ7mdCIMKNmtzs7zHC0",
	"Iujp7EljM9fX1zMMn2dcLPdsX7n38vjo+euz57tPZ09mK5UmBlWUviaTGpAOT44n0/JYJ1f7OMlWeN+m",
	"eWA4o5ODybezJ7N9a6AFPNAMxd7V/h7O1WovKtTUy9Aj+jNpVIytxFvMiuQKlLPjWG85V05LDJHHkGYF",
	"5n365EmtRKSXfm7vv61KyaB936XwZgHEq+U0+FWD4Lv9HwJyQQ5+AGXJAxIb5T9eykDV3nf6WwVgNhMg",
	"aQXZb7aBFiBqoIPEOGGQuV5wUC5XJnAQgYTGgVG15OGWBjyAbrwiOCaivGi29uqfRUXiAtb1S/4ufHa1",
	"tcDEMCvA+8l+WxvKylaDT2U6+dsWMaaQcRvYcmylNCMdPBeCi8Eo4RelNVXtnZxgNpkQFXzfIHOPVxX3",
	"zHS2EfFV95Iqspi+rV3lXd66dhjaG2cw4I7nestsNd0/icW7b+9h1hdczGkcE2YQ8z6mtHWc37JCrV3B",
	"y1bcg9iOIG0CQf5WaKd7diJdJ9WCBBOWBSsaapJlkhI6lyqoUFpI4zZNs5f3zTInMIIeAHLLmBQ9qt5o",
	"xyU627GpqqyVIRPkCnLnVfOAOZIJCyopZpEIr4tYTkNpVmw2JuPhrgSNVJm+C/w1bX42ly3HZFGhwuR2",
	"ktWSreSKiHWRRDG00KSSGPL+VguwlVMnA0C2MZtsSYP4kqCdH3emaOdH/f9QV+RfftxxNX8vJpdkvf8j",
	"nNv+9JKsn/6L+eOplRxCO4UZb7dTvzaLn7bNIF6xST+ZXJko7rxM3Ae5eUyWsnZEq3RHdFHFcigMbAat",
	"ZeSDAmQrwhrFX8qLA+EUXg48gFArZtAUUmqUcOq1zLY9/1uhd61UBPTEHW/LfbxjP+EYubQ044P2WT1o",
	"GQ+ZEUwRe4QHvGrNR810bu05MaIukeonHq/v/gIYkJXStRI5uWncxP37WkgI0PF4Fe/6Kn735O/3cRXh",
	"ixahE2r0Rp89CRgkdu39pZ+9my7py/xeJRnIXgBUXv2NxK4hYrvv9d9PrTQvZlZaPOy2fpB9122+8Cq5",
	"uIVMf/+k5CsTFr978t09TPmaqxc8Z/FDFk8FwSZNcsn3Rh03rnpDTwmO7/l+Lm2p3Y++nNNJzugfObHp",
	"YeHhH+/reF8/I+47XMkd8njekvuGvvd8Y7MinfS2HtSh8sEuTP3vmx1mJU3qIOngE5OIUTD4kujS/Ygi",
	"D0oImU6yPMi5QP7eGvNytAHzAv3vmRoap4lPQg7vTV3ySQniqK0ZifJIlD8rzdAezjLBbcavIC0/hAYm",
	"MwVh6y7utsnUGte21g6HbvKt0XNTp8Vf8EjPRwZ3pKWfES192Lp26/Y4wJ/J+LP3Oy89syOOnkpfiWHX",
	"oFCPW1I/9uhmJe6MDkejw9HocPSFOBwFcMQmgEGLBC+hrqupMWdyvOnVpCkW62r0k5yhf+qdAKg4Ag7X",
	"5jmzYAFIVtLFwc23g3lxQjYEBgAOdbp2DDZV8H6nhFE9FAbKJu7YgfVQO5DZSeStV99rG8KyIiHOnRqG",
	"DH0dXbHu9cV+zZVLm/05vtk9nle1h7vNzco0uyOfKjv4PTtQ+bOO+rfRW+qT3dGmuDbAD+qZ84PqvcC+",
	"2Lap5qo2+MNya2q/4KNPxNfgE9EnuEJ4ZP/9OSU43trt2ZrT0Xh1xqtzP/xjt+9Q7/WBhlu7P6ML0Bbv",
	"8MjajuaQL42ZbnHxMZbdYc89OPNsjWI9CDedTSTw+6NQo7Q/ksSRJN6dfmEvJlCzQhYph0Kks8jhVGrq",
	"jR7A69vUOZQft6h5KAd9EPTUh8LI/Y2k7usRG9tJjiAsJnADOpJWGaOfaeilRqzSmJ+JOrVttqmeCU3u",
	"LKtlgdZt0Z9pa8GfS8avWbGQ31xiw7D1ERqfVttOPlfl0VNzOeq4jNzkI6EYeaJPR6DKHNyd5MlPP7qB",
	"CvnM5eIfFcmjInlUJBeK5I2vlKdW3tqdGpXLo3gxEpOHQUw6lLy3eJ49le/WqMmo+B2px0g9Pm/lBGGC",
	"J0lKmBqQSrtsXHE1DikmnhdNi2zag8kJHhj/bYIhILE+Q1TKvJpwB8qvZYJf0ZjEUz8vvHWjXpHoEtG+",
	"CEXrbS3Dk4BXNXiwU4kiLEnh6E2dIsV6ydchAjVXcJLYYpG679SWcSmg7E9knOVh5XNiCsm1RmFI8cl0",
	"H42DH2ncl03j0OdF5MrbEwwHbHweEhlY4vTgDOeNLmO84FcTLxhCwa7QwY3QS/cIItcYUDgGFI4BhWMG",
	"8w04tDFz+fhgtT9Y3XFzrOPZaouha/S4o3C65jz3HFnXsoDR7W4Msvvs5aENQu82owEtgtGmiub2KR9W",
	"cN4gGjHaiL8GxewGAiOE7G12704Jju/41j0QX4zxyo1Xrpvl7Qz12+zaQac7vnejv8bd3P2RGx8dPh98",
	"ytkWEtcVHLgpYwFeI3dM4x6EF8ktNQ6fhLyNio6RtI6+9J9QtXKLHN4BwhwoxG563QE9fnBZuhtbKDKX",
	"f2q67BbSb7IfKeUo9X4uFGvzmKAt6Khu54g8aqrGO/uVa6o+6iqG9VZ3cRdH7dWovRqJ0Ki92pL26iMZ",
	"kLAu6y7o3qjRGlmgkQXantiySAgZ5Mf/Qjfs991/YcYb/fW/EvdHwJ8eH/1e1NGtCsQZffFHX/zRF/9L",
	"Le5zbCM826r4uE0DXWlbCY5tQhx5Zgb5dEVzgGyNQQDjK0iGOP7XnsI2X39odUf+/Wbse/bp9yYdzduj",
	"H/+nup4NuWfvL/jvzZ4iaZZgpdkjSTnrFIhiVzwn4olmHihn8IjZIVAxRlhCOrftfiub9epHoAqdeykb",
	"E7VoQxYeFfn0VplRbHtAYhuwnP0Irfmezxidp6P0OEqPo/Q4RnKHSGeNbo0i3PgibsgjDgj2LFjF+iM3",
	"jDf86Lf07p7SutVu4MyflaNQHdojb/qV2sh6uGFBcGxYweId7L3PpwTH420eb/N4mz+nl3x4YeQ+Ra1n",
	"7d7UwaU69MNKvNCqyB2v1vhQ2prIfVdHP41bujhb9Ej/OiyV49Udr25PTea+6wvttnR/Ry/27V3fUUM1",
	"eq5/YfbavnLM/ZwGOKZviVg9CNfzDdw77o02jZ4kIy0co3i2rsfoCywGtWUZ1FNVYDqa2CKa3S50504F",
	"tFE2GmWjTysb1UuDDZeUtnWdRnlplJdGOvIQ6EgefJBBHNn4TS6FmG3RkVGUGTmB8QYP47kFybikigtK",
	"hsTJnrrm6/5g2VN/6NH3+ivxNCsQat0TNzsMlXTTGiKNIbSjE/ToBD06QffSsJLCjP7P46vkv0o9cayB",
	"p6ktmLVsekcRrd4E9xzWWp95tEiMsa2f9N62iC2bOD4Outk18WW9qUYiMMnD8oPsvvmjruBr0BUMkeOM",
	"R+SgO3VKcLz1G/VA7G/jdRqvU50B7fZSHHSlrP1py3dqNMJt+V6PvPHorfPgvXXq5KvTcXEgQwCGv63T",
	"rwdh/NtUqL9fmjUqEUZCORLKbSssrIlrzaJhhlbT/mzNoiGm1rL1aGv9irTaJVL1WluH4ZOxt5ZtR3vr",
	"aG8d7a2jvXUYr1fSjdHiOr5N1bep1+YaeKDara6VF+puRDRvinu3vNbnHsWm0fb6iW9wmzCzmfl10CVv",
	"CjWbK4cCEz00I2w3ERjtRl+H3WiIiOcMsYNulzHF3sHdejDm2PFijReryZ/2mWQHXS5rj7yD2zUaZrd+",
	"w0fWebQ4fAEWhzoh6zHODmQSrHn2DijZAzHRbir/3zf9GjUOI9kcyea2tRs2v3Jb2hktaUkzsp8+uko8",
	"fyaqzIp9Z1RiQCror1P17M7wHXQ1lh3zYOUimRxM9ib60bCt6wf8xp2kRAsukCYIhCm7g5mX+7TyYdI0",
	"SXkDcYaOiFB0oVuTM7pklC3r9b+lN3hUtpamtShoYfc8Jh9rcFCT2bV3hPYK5f5gzcLLfeMG6uRWUrz3",
	"9W+LF7aDeI4X/SO12cKLsTza0DmaRhFBIkKvKFuGCIMd0aHkzbub/x8AAP//HCzjDU7uAQA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
