// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/v1alpha1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w97W7cNravQmgXSNOrmbGdNEgHWOx1Hac1GseGP7rY7fhuONKZGa4lUiUpO9PCwH2H",
	"+4b3SS74JVESNaNxnOwFWvRHx+LX4TmH55vMb1HC8oJRoFJE098ikawgx/rnYVFkJMGSMHpM737CXH8t",
	"OCuASwL6L6gbcJoS1Rdn540ucl1ANI2E5IQuo4c4SkEknBSqbzSNjukd4YzmQCW6w5zgeQboFtajO5yV",
	"gApMuIgRof+CREKK0lJNg3hJJclhjK5WujfCNEVmBOBkhfJSSDQHNAd5D0DRvu5w8M0LlKwwx4kELsZR",
	"7IBjczV99PDQ+RL7aDjn7I6kwC8LSPSWs+xsEU1//i36M4dFNI3+NKmxObGonATw+BC3EUlxDur/TeSo",
	"3eF6OFK9qr3t/+9//09zRyhjdBkjITGX6J7IFcIoAymBI8YRLfM58FhjImFUYkIRZeh+RSSIAifgIcRR",
	"K4CQ3yJGYcC2T3K8hADy9BSbBh5hiTO2DA69ebjZTKJLiWUprnSPNjZNG2ILhJEgdJk1kcsokitAKdwR",
	"gwugZR5Nf47OORRY4yNWc3Bpfl6UlJpfx5wzHsXRNb2l7J5GcXTE8iIDCWl008ZpHH0cqZlHd5gregq1",
	"RGcH/pqdRg+ITlsNVafJgdlpqOHuNHkbaSJaXJZ5jvl6IMKzzMe16Ef2D4AzuVpHcfQGlhynkAYQvDNS",
	"m9DWa/R28Rbv7RPAZ7NDBe5DHG3g6o5UTVaYUsi6CL2ABXCgCSDJNP5sT7RgXP/t83OBk1u8DJ3qOLJt",
	"A1bQImfX6QUreTJk9sRgZccFHuKIwy8l4ZAqOtvV6l3FFQZD0uKIUaOpuvBVTU5ACpSCxCQTGkJGAWFR",
	"QCIVT2v4S86V5hISSzAfiUCH5yfoAgxYCvwmdTMs5BXHVOiVrkif4Ff9kNJyZqUKNFmNhRQtOMs1XMKc",
	"NckQpkyugKuFF4znWEbTKMUSRmquELVyECLIDD+UOaaIA061Vrb9EKGpphFdVtjBc1ZKC3EFXpA12FwA",
	"v4P0e6DAcZgMavfjHCROscTjZdUTyRWWLWzcY4EESDTHAlJUFmbZauOEylcvazgIlbDUOijigEVo8UP0",
	"1ZwTWDxHpkfFm9Waz8SgnRqKqAU2ajs3qxEZUaVxBw7Tkrd9IvQMFQRxiOUqBNT033hYLqvd9Mn4Bo5i",
	"zZRsga54CTF6izMBMbIC0Zf3qj2KI91hZwnfgs7O1frqpm59bgjnBja7/Lgu9F5qriMUHeEcsiMsGtrr",
	"sCg4u3Nqw/18A5ToH28xyUxjkoAQZJ5B+w8nN84xF7rr5Zom+sfZHfAMFwWhy0vIIJGMK9r+hDOimi9Y",
	"lrFSnii9suQgVNt1kWJrKCib1XU9LTNJigzO7inoOd5oNfwGEpbnRAjCtAkxjAbHlLMsU/b7BfxSgpDe",
	"xo+U1FsoYQGXZKkm3aFPhbXeHhU6L6BggkjG10FcKhT2NnQQ7jdWyH+bAcgeCug2h1v9R4gWBsceRcwH",
	"ny7my1DqGL5dkGXbLRlmn39PZGD4NuP8x3IOnIIEcQkJB7nT4BOaEQqPWPUHKYvQMI2DonQUO2VUMcFu",
	"7llosJmYM3r8sVDkCxsLnFEEVQdkdI5WF2rutMyUhlRKV4xnVOk024MI9OFrZP/7MEUjdEpoKUFM0Yev",
	"P6Acy2QFAu2Nvvl2jEboB1byTtPBC9X0Bq+VXDplVK6aPfZHL/ZVj2DT/oE3+G8At+3ZX41n9LIsCsaV",
	"z62MF6x4XYH6QUF8antiurZe91cwXo5jPQ2haKVAruaDO+Br/e25WvfD6MMUXWC6rEftjV5/0IjbP0CH",
	"p8qIeY0OT03v+MMUvSNCVp334/0D21tI7c3uH8gVyjUOzZjJhym6lFDUYE3cGANMe8SlcQebe3ldo0Tp",
	"ttfekBk9/oiVZ6Qwh/ZGr+P9V6ODF5akQXPAnOIuG5nviINiJMWZCKNitRYkwZnnHzVtSFyQn4CH+fLw",
	"/MS2oRQWhFrw78w3SJHh/MparVa2bvACYYqMBTBGl8pY4wKJFSszHTe4Ay4Rh4QtKfm1mk04iz7DEoRE",
	"ytDiFGcGpSbokOM14qDmRSX1ZtBdxBidMq6MywWbopWUhZhOJksix7evxZgwdXTzkhK5nijbnJN5qVhy",
	"ksIdZBNBliPMkxWRkMiSwwQXZKSBpdotG+fpn7g96CJInltC0y4ufyQ0VecVI9PTckiFMn3CV4Auji+v",
	"kFvAoNVg0KNrjUyFCEIXwE1PbcOrWYCmBSPUmrgZ0Z5FOc+JVFTSKk/heYyOMKVMB4FKpU8gHaMT3yL5",
	"3KhU2BMjhbIwMp3tvs2KPdM4OgWJtcFs5famEbXSHG5i2zHWvm6Zyt5JskzggR+yiM1snUBJ14sPh/Ra",
	"PpV2r63x7Dm/QayqQeuwt2Rie9ZGVY6rYrP7FUlWCHPQyymWG7iMDiAGbP331SquD3LuXMiDHwf9rmE0",
	"C4f02sTTKHaI8SCvVhlEwGbQJuQRCtPBEWql40daUm6MaTX5QR3HrfygOikjwUhv5Vw7EaNdTj8+8iTu",
	"5+aIXifSsg2rxkjrQ+SRFy2pfUaDL8W4C7Lsoo0DTYFD2qvvLmwHp+F6590cRWqvs3GTgmW9qtw2+xrd",
	"usb6c8IohcR6kRWxu/sWxqw8eRM+8bYZnbzxAxStFcKMYUaeejK6xe9VJqdaxUlEJ0MU3ArPt7D+SyNR",
	"k2Cq1ZKAVFkEhBJJcEZ+NUEsaR1pCTwnFGdxBbNkbliMQCZ95MLpGc3W0VTyElqs2dpV7CGwn5S+U9VF",
	"hJvMhrewY6m06Yo53dylocR8CXKYfvJBudLjwqEdM+WwLXnzdAM3BSRkQax1mIJQK3S2loNcsbR5pPyA",
	"xzUF7f/r4IZyiNcXIBrwbYodbILYm3lTt+aqFRZOlMLhRPYKdSvsWrKIuGHdHX+iMDcsVAnyeqEnEePB",
	"TdstPk6Sb5hrSwxwAw6rjBoWohkQq1NQ11Q4z3MnLmoBXC0RbK3WDbbWwPQ0exBWCHtHFpCskwwepf0y",
	"N/pJWa09uV37kxmttdfHcVhokj7WqhRHD8ZqceQoZ8KSlsbNyFnzy45s1oK6zSqt5gYUgfYQaFu6NZju",
	"TLhgV8gSMa3INM2tpDcKBJ1dVnZDr4zLg1mhq8YkupN1Yzi6vni33dIy8/Yzxpl41BE6uxy8hZ+alqLb",
	"RvBc6JY3ZAlChnGR6rb2XCaKhMQKH3zzaor3xuPx86GoaS7aj6gqUr0Tuqo4yDYdlxTlMHHQhMNIgzhK",
	"ibj9lPE55IyvHz9DC7VqN9WkFrqhqO1JC1mLVliP2AR/DLJNlKlb1PA3zO1BP+JEkgRnjy5vCAHqV090",
	"W+vFQ60eQKFmB2Sozc+leRGaHrHUEkp4Q5Szdk67k+mgcNMHR4VND2jsEwn5Lg5wKyXhaIA5x2v1t/Ek",
	"+wEx7Y+AIZgRCS2vXCXRUy3gsJFIclf7gtYJGg5L08UNgNHyEHZ3bnQVwEA4rH4zUSkjtQL+qgKtcQZz",
	"k8uxFClN9cBwHLRSQiEsiLWQkKc9vrlpRAK42oSOjVuQukyuUwznWErgNBh8cpTVHVFhezY204lXmXSG",
	"g6OkRGoVHZuqQMb1/5WVKMrFgnyM1SeMxAqybCTkOgO0zNjcLabh16vjJSZUSFf3kq1RxnAKZgkNU44/",
	"vgO6lKtoevDNqziyU0TT6L9+xqNfD0f/2Bt9O53NRv8cz2az2dc3X/85pHWb+A7VZZrI9znLSDJQSVx7",
	"IwxbPfTK/z6V6rf6EZ6w/S28ikMr5JAdm2Pt+pHMRE0TWeKsLiP6VJloTSJfNNam/w5yoBvmDpwF3I0h",
	"7jx7KwZrxJ0JQ4kNdVoeDTQeTTjaxWMVHoNVWj56h0poWzO2US8MEqx1gFRZl861fJSHr2bIsJCXAHRI",
	"EZllC1MzBRTN14ZNjZwaXjFW+V6Pchd3VADVmIYK2NUm1EJ7F+bsMKSRpifWGx8wQd2/ElfpLpIq7UlZ",
	"eSejAVXzJEbhg+mj0We/io01bWp4a6x5rOZzQL8N/fi0iserK8zTe8xBZ5BNJQKhS6vaUCOn+/TpFguD",
	"q618ukjdE6Radqq/DofhznQ9TrjU+gLmjNlKpXN2DxzSs8XikU5KA1Zv1U6bB0igtemCNJp8cAPNjR0E",
	"2gMOTOO0B42AqoetEACtekkqJmVJUm31lZT8UkK2RiQFKslivdHhxkugsjfPpcT54VLfkzFdglzop+57",
	"5vB6KPVpinzmbdA6MysEh7JR3zEm0cmbXaaqzrHBYRjOs+qwX7rDPnCBdorfR0m1jy4UcZMA/UevY0hu",
	"Sa4UuqeOt+WY4qWpnNaixYhZfcMpycpUtdyvgLrvru5mDihl99Qa20oUatkOaZeJXL9LU4O2VUWbzVS9",
	"K1X12PEPW9CWPiq4Z2B6+jxMY/qnlPCNzT5Ownen2CE8XiOsio0XV+wNluoInJXybGF/exWpjxHtDSC9",
	"JQKt/qrBwa3S2GarL6GJuH36ms+45xBb/0mfXtNfn18iblEpbNS4yZQFVu5vOFbMddnwWrnWKy8uoKdv",
	"zrlZqOk1uryj0VP6FysWuMyUQb+nrLouRDn+SPIyR6kdhHCWsXu/oMfUKkiGEnsXzNy6rAbUIkpYqZci",
	"rKsYmTpLdzYjCGqPdu75WnlmyispKZFjVNeaVh8Fwhym6IMwZZsClNUrYvQhNx9MJab6sDIfdM2ppkUd",
	"cfjqr9Of90ff3sxm6dfP/zqbpT+LfHUTDDh0yti7BOx0aRZt2ioADQzW9e04U2gzaeyNLv0fxZx/FHP+",
	"Dos5Owdqt7rO7vBHlHhaSENauOdmC84GiAbXtb5IGDZCKkHhRaWsxNBX4ntLi7C7QdOB5cRczwOhLEm5",
	"Am6zfkY6rbBAcwCK3AQezeeMZYCpiSrNIfuUe/2Hzh8yM+mLiUWRrZ1o6Rjv3h38JvHsPneiUG1jDjMI",
	"+kndNQu2LLqN4l5M+FNpf9iTkdZKFEtbAOxT/14pZo/ww8J9bsR3fdXHzSJm1ZcPcMvqWWN/SwGjJt6R",
	"BI8IzAcQXxFoHOS1sOcX7Ga0jtfRrNzp+0y4ygodqg6k5AUPk+D8+HQENGHKPTz/8ejyT/t7KKnvzSFh",
	"Ls75PBU4wM3Mx/Ca+s8hL9xVXxucRvfEviFgRQgRVThbOcxKrXokJCIk4HpkjMLqIPHS57r2dNyNDzuT",
	"9B18o4AeJc689ErNHNs5SnEPpD5DBRloY8qme1Mewlv+1IRMf7Q8ROO3JKuKFVpnjVEJtEfEFhkmFEn4",
	"KNFX11dvR6+fI8b1JfRXLyu02Rncbhck68Wb6neshtmUeiuewe5dhbc03gZXAkuvMkan9kEYIFrbzyIN",
	"3CxSEM0iA9MsGqM3xhfUurjq5EcI9KcotkO6YYCHOFpyVhZhlKjtPRNI94g9X9CCpV1CVydGyxw4SdDJ",
	"mzZYnDFpoOoaoiyFjUsXwG2NAVJ9x+jvrNT2uQHGRA1zZU0vcE4ygjliicRZ/VYO1hG4X4Ezdwtw79XL",
	"l5q22IjwhOR2gCkJD415ebD3XDkIsiTpRIBcqv9Jktyu0dx6tqgqIR2jkwVSDkCFsdgEDZub0W6l2qcS",
	"ezXCFHjhezb9QQg8FywrJVQxCMecrRss6D2TYAQxpmsEH4nQPpLuqsXxHJDS9fecSAnhmFkpgG8kGrun",
	"wD8Dv4TiJdVRC4qC8I3ojlxYEnmhBFNoT9x/4ASj74ls1qBobQahKhBWUnlekcwFbSadmI3q425hGDo9",
	"E4YiNiXWsvvcxXh1PNTQOlqjl2yoR/99mD7m8XnGFjxZaOpL+D3XylzzdiOynqryw4NzGmPpAu5If8qE",
	"21adjhFQO+gb4e1cDqqA76wa98Xi4g2vevm7bdWNbYfGXnuzjBhauOfCfIeXV1IWA5mZoh+urs4HsrNi",
	"yPMgD23lX8k8/nUalIMsOa1TPxoUAXfAPYbeJIZ24T7e5T7HPNiE38SaJmgDX5qqqtDmeWUNXF+8M7I1",
	"YTkIhBfSeupK++pCanQi9X0qkxoC9EsJOnDMcQ76uTdRJiuExRTNooniwYlkExd2+qvu/Rfde4h8bHB4",
	"Rb4vz9SOI0Mr9z4p1+Hrnrrv7vtT7rasLdr+pHeo+uvaex++6AJukuMbygCNDSAZSjhoU7p963SQ/VyZ",
	"vYF6ps9LYLvDEJo2Pi4yHf5k4m5gxpHQqw1V6jWUyAzcqs0fr7/NAgOV9jCE1DAHJ9AvQfbPopu3ThWm",
	"fD197GHoZpt3bkfXRAqxzqmu6/88D8F4ge0OXuo2RER9TdYYzVmmrHhBhITUu3ahH/Bc4TuILaWtgBd6",
	"hNmTUOqG277mpAfCAZQyWZeCPjLyUnc2D6l1agI7yNbw2IfEhMR5sSEMaaoydfbkHgu7lR1ijylk8Ji1",
	"rHuih++y3nLDu3SHSMAvpZYE9sGFRu4IOycmQd6bdVVa3lywNYE9dM6KMsNeMYs5/WN0ATgdMZqtBz5j",
	"98mBt1NcKBhtSuwW1qJ+TNeG4VqXuhlfYkp+NSV5CZawZFz9+ZVIWGG+Cv081nPHzEEuGiaubO4yWEWk",
	"PMcQlbzcHZbKwRQuOWq+x0oAz3QqaKLWmkX2aaa+9zD0qP4cLUWswL+U4JCol7UVX64GyFjKz4SXTK0v",
	"odU52kFP8FZPlB1mwOWFLdJplQH5IHZRtCpzTEdVhUwrNK1NIDV3OE5c9h0QV3mgZKF0p5IpK71WafgO",
	"uDK1SvOWpPeEyBwWjNuFCV2O0VtNlOnmQoJn4lmzQuBZ/qxZIfBs9ay3QmA2S/+jvyigAJ4Alb3XIOt2",
	"hTWzIxO45mS5VPI7hEkjO4zhcQdDir8b9L60g8JFRW5Gj0yNfTSP/8025mos1i0/sq0dnnERxeB1N11U",
	"OazGqBeWeuLeLt6KvX0MKN6m3ZUftVWitpoTiu2H3Dz9p34enV/3RqbD79GZqqXedEpPRZMzbPrG9Zs9",
	"D5WxsH6vBW1kK43c9cphrwT27Gbbg32b4NqSWOrBxEOAShtrL8NlW7gRUGqZU06abrpjpjshrnqN0RnN",
	"1uZVYP21AI7cAdQZKCOldr53Vov1gHfmk7H3SmrjNlzz9lnX+8F5kRG6PFGKKVjdUIl195y+K1rTQxUi",
	"voCkrgq5+sR1SxL6eIp92gZ2HBKDWx68JabkS5ac2joiBXiCM5e7TBl95gJXSL/I7FtDf1SAfd4KsCSY",
	"K7osl0vQ3pgOIFriJC69ovFnUrIx2kPE5mWMi+vb4i8Ogrb4H2VnT1p21vMq+RDj1a8hV3gsrDfW965e",
	"z0vgOU5WhELvUverdWsBRWgb3Znp121KrtwLe/kSnViADAsQgSAvpHYAuf6TsmahwB0mmVp4jA6VZygY",
	"RUmGuXErXEheuLqjFNC8VJIHhOZcZXlzkgIicks9+6Z7QzXy0Jl+03uKZtFlqd9TdknmaqefnW2Uiz3C",
	"NB31PmUzoPqvehhdi4mBT6FfkRz+wVxw1mXo3jFjYrb0sHJ8flWWQeUGcmGVoUbqyeH7Q/ce8OHF8eHk",
	"3dnR4dXJ2fsY3WtmUB+b9cUKYYTqegKOWAKYGjnsRlYpVF17jbkkSZlhjgSRoBPWxD6gjzng2DyGax6x",
	"RYc6u4on7+H+n39n/DZGx6VSUJNzzImzc0qK8zlZlqwU6MWo+ldnjJOn9tpKbKOvZtH3p1ezKEaz6Prq",
	"aBY9D3Lhdee6Sfu2Va317MPKRlzjUjJ1UJLqboy28GgaulUjlSW/tLcI7et2CnJWhupstr7Z1noc2hwm",
	"Lr/nOAG//n6jqev6KSvPY65NYyom7LB5KKf9oG8YmxsyOtWR6I1BjkkWTSMJOP/PRUaWK5nIbExY5KIy",
	"2pB8q1vQkTqoLENXgPMojkquhrqj3RjdiS393Jzi5qvQsOfu+pyp89IXIUBJOawtSX1jCnJbR7PIAKQW",
	"TZAuXQTdRKzkCghH94zfKlYQ45m5p5oAFVDnC6LDAicrQAfjvc5m7u/vx1g3jxlfTuxYMXl3cnT8/vJ4",
	"dDDeG69knhmCScWsUQtJh+cnURzdOWMuutvHWbHC+/bWG8UFiabRi/HeeN8mjjXDKUk3uduf2P1MflPA",
	"Pkzcm5S67AACpUjfg7QpS/sGZupek66dnEp+n6RmhHsw075IrcBwKUXtD24OyNn3qiVDy/biou15ac9H",
	"TWKrLywJqmdbHfua5xwNjwdClt0a3Opqu74UhFpvd1bL6hxova7ufNF653PTujc6+lcwxQWq/WBvr1UZ",
	"5iUKJ/+yVkQ93/YKSnNGWzmFHxW3HOy9DLzAy1xKXHV5ubf/ZOBUtfMdcK4pLuVKh3hTs+rLL7Dqeybf",
	"spLaFb/9Aiu6f/CKLjLi/jE4vNRhKHOqohv1reeo1rZUUQYO6rW9YNiq+Xyz7bheQJEpleKX2z7uwDZK",
	"GarLgU9xOm9MZxDyO2YeqH7yA9IE5uHfeCxfPuFa/bz4HU6Ru4f2uznoWw5cXd3t/Fh92ljoqt6RqY3A",
	"FIUu7fUdNjOqexPw8/B3d51BrL7/uQEIYTL93bH+iy+w6lvG5yRNgf77lFwcffNFtnpprPtrWoU0Gue9",
	"c7a3HX2rdjcaxjue/gvAaejs76Rs+xe0FvOTKt3PpAMHCQanDn83x/NLW73/fw+mzlzrMLQ+EcaJnuh7",
	"enZcp0zKnTT9r2S0LFIdxLPnwCr+rsfXnKH/mPmTdYF/uHn4vwAAAP//b3fW2fJ6AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
